//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAES_SIREGU.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class camioneros
    {
        public int cedula { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string imagen { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public string tipo_sangre { get; set; }
        public int id_tipoempleado { get; set; }
        public string matricula { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
