//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAES_SIREGU.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantenimientos
    {
        public int id { get; set; }
        public string matricula { get; set; }
        public System.DateTime fecha { get; set; }
        public string observacion { get; set; }
        public int id_tipoMantenimiento { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
    }
}
