//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAES_SIREGU.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculos
    {
        public string matricula { get; set; }
        public int motor { get; set; }
        public int modelo { get; set; }
        public string imagen { get; set; }
        public string marca { get; set; }
    }
}
